apiVersion: v1
kind: Namespace
metadata:
  name: frontend-team
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend # this label is used to select the pods
    spec:
      containers:
        - name: frontend
          image:  httpd:latest 
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: frontend-team
spec:
  selector:
    app: frontend # selects the pods with the label app: frontend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP